inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.3,7.4],[-0.3,9.],[-0.3,3.]]
  marching_cubes_bound: [[-0.3,7.4],[-0.3,9.],[-0.3,3.]]

grid:
  hash_size: 12 # 0.13

data:
  datadir: ./data/scannet/scene0059_00
  output: outputs/ScanNet_feature/scene0059_00
  trainskip: 1
  exp_name: demo
  ds_start: 0
  ds_interval: 2  # if run adaptive interval, ds_interval must be 1 !!!
  run_interval: 5
