inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-2.6, 5.6],[-0.3, 3.0],[0.2, 5.1]]
  marching_cubes_bound: [[-2.6, 5.6],[-0.3, 3.0],[0.2, 5.1]]
  

data:
  datadir: ./data/Synthetic/green_room
  output: outputs/Synthetic_feature/gr
  trainskip: 1
  exp_name: demo
  ds_start: 0
  ds_interval: 1  # if run adaptive interval, ds_interval must be 1 !!!
  run_interval: 10

cam:
  near: 0
  far: 8