inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-2.5, 1.1],[-0.3, 1.1],[0.1, 3.9]]
  marching_cubes_bound: [[-2.5, 1.1],[-0.3, 1.1],[0.1, 3.9]]
  

data:
  datadir: ./data/Synthetic/thin_geometry
  output: outputs/Synthetic_feature/tg
  trainskip: 1
  exp_name: demo
  ds_start: 0
  ds_interval: 1  # if run adaptive interval, ds_interval must be 1 !!!
  run_interval: 10

cam:
  near: 0
  far: 4