inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3,3],[-4,2.5],[-2,2.5]]
  marching_cubes_bound: [[-2.2,2.6],[-3.4,2.1],[-1.4,2.0]]

data:
  datadir: ./data/Replica/office0
  trainskip: 1
  output: outputs/Replica_feature/office0
  exp_name: demo
  ds_start: 0
  ds_interval: 1  # if run adaptive interval, ds_interval must be 1 !!!
  run_interval: 5